### ISSUE TITLE
GraphQL [MCORE-9]

### ISSUE THREAD

**Issue by Schtolc** [Schtolc/mooncore#11]
Должно быть интересно и познавательно

**Comment by Schtolc** [comment]
Судя по словам Егора, эта панацея для запросов с фронта в базу, надо попробовать внедрить вот это дело - https://github.com/graphql-go/graphql
Если вдруг будут какие-то трудности лучше отписаться тут, обсудим

**Comment by Schtolc** [comment]
Для некоторых моделей уже появилось. Будем продолжать работу в этой же задаче.

**Comment by Alsaril** [comment]
В запросе usersList не селектится фото
