### ISSUE TITLE
Изменить модели для облегчения авторизации [MCORE-12]

### ISSUE THREAD

**Issue by Victory12** [Schtolc/mooncore#21]
Модели мастера и юзера должны содержать `UserID` - ключ в таблицу, в которой содержится логины и пароли. Это нужно, чтобы логика авторизации была одинаковой для этих моделей.

**Comment by Alsaril** [comment]
Ввести авторизацию в GraphQL

**Comment by madsunrise** [comment]
![mvimg_20180121_170006](https://user-images.githubusercontent.com/17799871/35195169-91fdffee-fed0-11e7-85a0-75e1dff37aa4.jpg)
