### ISSUE TITLE
календарь для записи [MCORE-34]

### ISSUE THREAD

**Issue by Victory12** [Schtolc/mooncore#64]

**Comment by Alsaril** [comment]
Спроектировать хранение и быстрый поиск по расписанию мастеров. РАзработать методы спи для получения информации и различные фильтры

**Comment by Alsaril** [comment]
Уже открыто: [#43](https://github.com/Schtolc/mooncore/issues/43)

**Comment by Alsaril** [comment]
Уже открыто: #43
