### ISSUE TITLE
Обработка ошибок [MCORE-7]

### ISSUE THREAD

**Issue by Schtolc** [Schtolc/mooncore#9]
Надо провести расследования, и решить фундаментальную проблему `if err != nil`.
Необходимо:

1. Писать ошибку в лог (обязательно со временем ошибки)
2. Писать стектрейс в лог
3. Паниковать при критических ошибках, просто писать в лог при некритических

**Comment by Schtolc** [comment]
Сначала стоит поискать библиотеки для этого дела, прежде чем писать свой велосипед.

**Comment by Schtolc** [comment]
Скорее всего проблема решиться библиотекой для логгирования.

**Comment by Schtolc** [comment]
И вот еще, самый простой способ - изучить исходники больших проектов, например gorm и echo и посмотреть(позаимствовать) как сделано обработка ошибок/логи там. Сначала стоит отписаться о результатах исследования здесь, а потом уже писать код.

**Comment by Victory12** [comment]
оки

**Comment by Victory12** [comment]
https://blog.golang.org/errors-are-values

**Comment by Victory12** [comment]
если кратко то суть в том что от err != nil не избавиться, но можно сделать красивее. Как в примере с bufio.Scan в этой статье

**Comment by Schtolc** [comment]
Как то печально, паттерн на уровне `errno` в linux. А что с обработкой ошибок в gorn и echo?

**Comment by Victory12** [comment]
при insert объекта в базу та же схема - вызвращается объект базы с проставленным Err
```
dbc := db.Create(m); dbc.Error != nil {
       #smth
}
```
 про остальные методы сейчас посмотрю

**Comment by Schtolc** [comment]
Кидай исходники в качестве примеров, так нагляднее.

**Comment by Victory12** [comment]
в исходниках сложнее я уже минут 10 пытаюсь найти где они проставляют эту ошибку и врятли это 1 файл

**Comment by Victory12** [comment]
по крайней мере в gorm

**Comment by Schtolc** [comment]
Наверное я неправильно объяснил задачу. Кидай исходники больших проектов, с примерами обработки ошибок, например в gorm вот так https://github.com/jinzhu/gorm/blob/master/callback_query.go 
Сам код простановки ошибок и функций возвращающих ошибки не нужен.

**Comment by Victory12** [comment]
а ок

**Comment by Schtolc** [comment]
И заодно посмотри глянь исходники стандартной библиотеки

**Comment by Victory12** [comment]
https://golang.org/src/io/io.go?s=12621:12681#L351 - стандартно
https://golang.org/src/encoding/base64/base64.go - 175 строка - err добалвяется как часть структуры но в общем и целом тоже самое на выходе

**Comment by Schtolc** [comment]
Итак, можно сделать вывод, что более квалифицированные, чем мы гоферы, предпочитают явную обработку переменных `err`/`ok` в теле функции, а не обрабатывают их в отдельной функции(`check_error`). Будем делать также.
Теперь задача сводиться к тому, чтобы правильно все залоггировать. См. первый пост. Нужно найти библиотечку умеющие в разные уровни логгирования + автоматически дописывают время и возможно еще какую полезную информацию, и посмотреть как бы печатать стектрейс при критических ошибках.

**Comment by Victory12** [comment]
оки

**Comment by Victory12** [comment]
https://github.com/sirupsen/logrus или обычный https://github.com/golang/glog

**Comment by Victory12** [comment]
в logrus хорошо настраивается форматирование + можно добавлять не только текст в лог но и специальные поля с содержанием

**Comment by Victory12** [comment]
stack trace
```
echo: http: panic serving 127.0.0.1:55307: qweqweqwe
goroutine 31 [running]:
net/http.(*conn).serve.func1(0xc420094000)
	/usr/local/Cellar/go/1.8.3/libexec/src/net/http/server.go:1721 +0xd0
panic(0x13fd620, 0xc4200c4c30)
	/usr/local/Cellar/go/1.8.3/libexec/src/runtime/panic.go:489 +0x2cf
github.com/Schtolc/mooncore/handlers.Ping(0x1664280, 0xc420068460, 0xc4200684b8, 0xc4200e43a4)
	/Users/v.suslova/src/github.com/Schtolc/mooncore/handlers/handlers.go:18 +0x64
github.com/labstack/echo.(*Echo).Add.func1(0x1664280, 0xc420068460, 0x3, 0xc4200e43a4)
	/Users/v.suslova/src/github.com/labstack/echo/echo.go:473 +0x90
github.com/labstack/echo.(*Echo).ServeHTTP.func1(0x1664280, 0xc420068460, 0xc42005d578, 0x1489a20)
	/Users/v.suslova/src/github.com/labstack/echo/echo.go:570 +0x10e
github.com/labstack/echo.(*Echo).ServeHTTP(0xc42005d520, 0x165d6a0, 0xc4200d8000, 0xc420066500)
	/Users/v.suslova/src/github.com/labstack/echo/echo.go:579 +0x24d
net/http.serverHandler.ServeHTTP(0xc420174b00, 0x165d6a0, 0xc4200d8000, 0xc420066500)
	/usr/local/Cellar/go/1.8.3/libexec/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc420094000, 0x165dca0, 0xc420128340)
	/usr/local/Cellar/go/1.8.3/libexec/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.8.3/libexec/src/net/http/server.go:2668 +0x2ce```

**Comment by Schtolc** [comment]
Да, очень даже неплохо, надо видеть такое при любых ошибках, приводящий к остановке работы демона.

**Comment by Victory12** [comment]
и при log.Fatal который вроде бы и сам выходит?

**Comment by Victory12** [comment]
просто такой стек трейс печатается автоматом именно при паниках

**Comment by Schtolc** [comment]
При любой остановке остановке
